((last-sort-comparer
  (bmkp-info-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("jurassic-test" 0 13
				   (bmkp-full-record #1#))
				 (filename . "e:/unityGame/projects/pokemon_Hoodle/Assets/jurassic/testjs.txt")
				 (buffer-name . "testjs.txt")
				 (front-context-string . "//console.time(\"")
				 (rear-context-string)
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 4)
				 (time 22062 55755 695300 700000)
				 (created 22062 55259 539917 300000)
				 (position . 1))
			     #2=(#("pokemon-coffeescript" 0 20
				   (bmkp-full-record #2#))
				 (filename . "e:/jsGame/cocos/gameElement/pokemonCard.coffee")
				 (buffer-name . "pokemonCard.coffee")
				 (front-context-string . "\n			when 'spark'")
				 (rear-context-string . " @getPosition()\n")
				 (front-context-region-string)
				 (rear-context-region-string)
				 (visits . 4)
				 (time 22061 38676 545327 600000)
				 (created 22061 36904 662497 600000)
				 (position . 24494))
			     #3=(#8=#("emacs-config" 0 12
				      (bmkp-full-record #3#))
				    (time 22066 56995 276210 300000)
				    (visits . 5)
				    (filename . "~/my-init/my-init.el")
				    (front-context-string . "\n;;------ Melpa\n")
				    (rear-context-string)
				    (position . 1))
			     #4=(#("my-note" 0 7
				   (bmkp-full-record #4#))
				 (filename . "e:/org-mode/pokemon_hoodle.org")
				 (front-context-string)
				 (rear-context-string . "[avg-document]]\n")
				 (position . 11172))
			     #5=(#("hearth-stone-core" 0 17
				   (bmkp-full-record #5#))
				 (time 22066 48534 272567 100000)
				 (visits . 2)
				 (filename . "e:/clojureWorkSpace/hearthstone/src/hearthstone/core.clj")
				 (front-context-string . "(ns hearthstone.")
				 (rear-context-string)
				 (position . 1))
			     #6=(#("clojure-net-create-server" 0 25
				   (bmkp-full-record #6#))
				 (filename . "e:/clojureWorkSpace/hearthstone/src/hearthstone/net.clj")
				 (front-context-string . "\n\n;; (close-serv")
				 (rear-context-string . " handle-client))")
				 (position . 1598)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #7="")
 (last-bmenu-title . #7#)
 (last-bmenu-bookmark . #8#)
 (last-specific-buffer . #7#)
 (last-specific-file . #7#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "d:\\Emacs\\Config\\.emacs.d\\bookmarks"))
